// shared/schemas/orderSchema.ts
// ============================================
// ORDER ITEM SCHEMA (for items within orders)
// ============================================
const orderItemSchema = {
  _id: {
    type: String,
    required: false, // Optional because not all items have their own _id
  },
  name: {
    type: String,
    required: true,
    trim: true,
  },
  price: {
    type: Number,
    required: true,
    min: 0,
  },
  category: {
    type: String,
    required: true,
    trim: true,
  },
  quantity: {
    type: Number,
    required: true,
    min: 1,
  },
};

// ============================================
// ORDER SCHEMA
// ============================================
const orderSchema = {
  // Note: _id is auto-generated by MongoDB, no need to define it

  token: {
    type: String,
    required: true,
    trim: true,
    index: true, // Fast lookup by token
  },

  items: {
    type: [orderItemSchema],
    required: true,
  },

  totalAmount: {
    type: Number,
    required: true,
    min: 0,
  },

  status: {
    type: String,
    enum: ["PENDING", "COMPLETED", "CANCELLED"],
    default: "PENDING",
    required: true,
    index: true, // Fast filtering by status
  },

  source: {
    type: String,
    enum: ["POS", "STUDENT", "ADMIN"],
    required: true,
  },
  synced: {
    type: Boolean,
    default: false,
  },

  createdAt: {
    type: String,
    required: true,
  },

  completedAt: {
    type: String,
  },
};

// ============================================
// EXPORTS
// ============================================
export { orderItemSchema }; // ← Add this line
export default orderSchema;
